export const S = {
  app: {
    name: "OrFit",
    tagline: "המאמן האישי שלך",
  },

  nav: {
    home: "בית",
    weight: "שקילה",
    workouts: "אימונים",
    nutrition: "תזונה",
    stats: "סטטיסטיקות",
    settings: "הגדרות",
  },

  auth: {
    signInWithGoogle: "כניסה עם Google",
    signingIn: "מתחבר...",
    signOut: "התנתק",
    loading: "טוען...",
  },

  dashboard: {
    title: "לוח מחוונים",
    currentWeight: "משקל נוכחי",
    targetWeight: "יעד",
    daysLeft: "ימים שנותרו",
    progress: "התקדמות",
    nextWorkout: "אימון הבא",
    todayStatus: "סטטוס היום",
    weeklyGoal: "יעד שבועי",
    noData: "אין נתונים עדיין",
    weightUnit: "ק\"ג",
    percentUnit: "%",
    todayWorkout: "אימון היום",
    todayProtein: "חלבון היום",
    todayCalories: "קלוריות היום",
    daysToFinish: "ימים לסיום",
    nextWorkoutIn: "הבא: ",
    inDays: "בעוד ",
    target: "יעד",
    completed: "הושלם",
  },

  weight: {
    title: "שקילה",
    todayQuestion: "שקלת היום?",
    enterWeight: "הזן משקל (ק\"ג)",
    save: "שמור",
    saving: "שומר...",
    saved: "נשמר",
    chart30Days: "30 הימים האחרונים",
    movingAvg: "ממוצע נע 7 ימים",
    targetLine: "יעד",
    actualLine: "בפועל",
    note: "הערה (אופציונלי)",
    alreadyLogged: "כבר שקלת היום",
    updateWeight: "עדכן משקל",
    history: "היסטוריה",
    noHistory: "אין שקילות עדיין",
    kg: "ק\"ג",
    current: "נוכחי",
    target: "יעד",
    remaining: "נותר",
    errorSave: "שגיאה בשמירה. נסה שוב.",
  },

  workouts: {
    title: "אימונים",
    thisWeek: "השבוע",
    history: "היסטוריה",
    startWorkout: "התחל אימון",
    finishWorkout: "סיים אימון",
    finishing: "מסיים...",
    workoutSaved: "האימון נשמר",
    addSet: "הוסף סט",
    exercise: "תרגיל",
    set: "סט",
    weight: "משקל",
    reps: "חזרות",
    seconds: "שניות",
    warmup: "חימום",
    maxHR: "דופק מקסימלי",
    bpSystolic: "סיסטולי",
    bpDiastolic: "דיאסטולי",
    bp: "לחץ דם",
    symptoms: "סימפטומים",
    dizziness: "סחרחורת",
    headache: "כאב ראש",
    duration: "משך (דקות)",
    notes: "הערות",
    noWorkoutsThisWeek: "אין אימונים השבוע",
    previousWeights: "מהאימון הקודם",
    vitals: "מדדים לפני אימון",
    suggestion: "הצעה לפעם הבאה",
    progressiveOverload: "+2.5 ק\"ג",
    viewDetails: "פרטים",
    back: "חזור",
    duplicate: "טען שוב משקלי תבנית",
    cancelWorkout: "בטל אימון",
    types: {
      push: "Push",
      pull: "Pull",
      legs: "Legs",
      upper: "Upper",
      walk: "הליכה",
      rest: "מנוחה",
    },
    schedule: {
      sunday: "ראשון - מנוחה",
      monday: "שני - Push 19:00",
      tuesday: "שלישי - Pull 19:00",
      wednesday: "רביעי - מנוחה",
      thursday: "חמישי - Legs 19:00",
      friday: "שישי - Upper 11:00",
      saturday: "שבת - הליכה",
    },
  },

  nutrition: {
    title: "תזונה",
    today: "היום",
    calories: "קלוריות",
    protein: "חלבון",
    carbs: "פחמימות",
    fat: "שומן",
    steps: "צעדים",
    save: "שמור",
    saving: "שומר...",
    saved: "נשמר",
    goal: "יעד",
    current: "נוכחי",
    remaining: "נותר",
    grams: "גרם",
    notes: "הערות",
    proteinWarning: "חלבון מתחת ל-150 גרם ביום אימון",
    alreadyLogged: "כבר הזנת היום",
    update: "עדכן",
    targets: {
      calories: 2092,
      protein: 190,
      carbs: 180,
      fat: 68,
    },
    meals: {
      breakfast: "ארוחת בוקר",
      lunch: "צהריים",
      pre_workout: "לפני אימון",
      post_workout: "אחרי אימון",
      dinner: "ערב",
      snack: "נשנוש",
    },
    searchFood: "חפש מאכל",
    searchPlaceholder: "חפש מאכל... (לדוגמה: חזה עוף)",
    grams_unit: "גרם",
    addToMeal: "הוסף ל",
    noResults: "לא נמצאו מאכלים",
    deleteEntry: "מחק",
  },

  stats: {
    title: "סטטיסטיקות",
    weightTrend: "מגמת משקל",
    proteinTrend: "מגמת חלבון",
    stepsTrend: "מגמת צעדים",
    exerciseProgress: "התקדמות בתרגילים",
    last30Days: "30 יום אחרונים",
    last7Days: "7 ימים אחרונים",
    noData: "אין נתונים מספיקים",
    completedWorkouts: "אימונים הושלמו",
    avgProtein: "ממוצע חלבון",
    avgWeight: "ממוצע משקל",
    avgSteps: "ממוצע צעדים",
    grams: "גרם",
    steps: "צעדים",
  },

  settings: {
    title: "הגדרות",
    profile: "פרופיל",
    name: "שם",
    age: "גיל",
    height: "גובה (ס\"מ)",
    targetWeight: "יעד משקל (ק\"ג)",
    targetDate: "תאריך יעד",
    hypertensionMeds: "נוטל תרופות ליתר לחץ דם",
    maxHeartRate: "דופק מקסימלי מותר",
    goals: "יעדים יומיים",
    dailyCalories: "קלוריות יומי",
    dailyProtein: "חלבון יומי (גרם)",
    dailyCarbs: "פחמימות יומי (גרם)",
    dailyFat: "שומן יומי (גרם)",
    googleCalendar: "יומן Google",
    connectCalendar: "חבר יומן",
    disconnectCalendar: "נתק יומן",
    calendarConnected: "היומן מחובר",
    calendarDisconnected: "היומן לא מחובר",
    notifications: "התראות",
    enableNotifications: "הפעל התראות",
    notificationsActive: "התראות מופעלות",
    notificationsBlocked: "התראות חסומות בדפדפן",
    importData: "ייבוא נתונים",
    importFromDrive: "ייבא מגוגל דרייב",
    importing: "מייבא...",
    importSuccess: "הייבוא הצליח",
    importError: "שגיאה בייבוא",
    save: "שמור",
    saving: "שומר...",
    saved: "נשמר",
    errorSave: "שגיאה בשמירה.",
  },

  redRules: {
    title: "חוקים אדומים",
    heartRateHigh: "דופק מעל 145 - עצור אימון מיד",
    bloodPressureHigh: "לחץ דם מעל 160/100 - ביטול אימון להיום",
    proteinLow: "חלבון מתחת 150 גרם ביום אימון",
    symptoms: "סחרחורת/כאב ראש - עצור אימון",
    allClear: "כל הפרמטרים תקינים",
  },

  alerts: {
    missedWorkout: "לא אומת אימון אתמול",
    weightStall: "המשקל לא ירד ב-7 ימים",
    proteinLow: "חלבון ממוצע מתחת ליעד השבוע",
    acknowledge: "הבנתי",
  },

  errors: {
    generic: "משהו השתבש. נסה שוב.",
    network: "בעיית תקשורת. בדוק את החיבור.",
    auth: "נדרשת כניסה מחדש.",
    notFound: "הדף לא נמצא.",
  },

  common: {
    save: "שמור",
    cancel: "ביטול",
    delete: "מחק",
    edit: "ערוך",
    loading: "טוען...",
    noData: "אין נתונים",
    confirm: "אישור",
    yes: "כן",
    no: "לא",
    back: "חזור",
    next: "הבא",
    done: "סיום",
    kg: "ק\"ג",
    g: "גרם",
    kcal: "קק\"ל",
    steps: "צעדים",
    today: "היום",
    yesterday: "אתמול",
    days: "ימים",
    date: "תאריך",
  },
} as const;

export type StringKeys = typeof S;
